modLoader="javafml" #mandatory
loaderVersion="[46,]" #mandatory
license="MIT Licence"
credits="" #optional
authors="CreeperHost, gigabit101" #optional
[[mods]] #mandatory
    # The modid of the mod
    modId="chickens" #mandatory
    # The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
    version="${file.jarVersion}" #mandatory
     # A display name for the mod
    displayName="Chickens" #mandatory
    # The description text for the mod (multi line!) (#mandatory)
    description='''
'''

[[dependencies.chickens]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

#[[dependencies.chickens]]
#    modId="polylib"
#    mandatory=true
#    versionRange="[2000,)"
#    ordering="NONE"
#    side="BOTH"
